### Listar produtos
GET http://localhost:8080/api/v1/produtos

### Buscar produto por id
GET http://localhost:8080/api/v1/produtos/1

### Criar produto
POST http://localhost:8080/api/v1/produtos
Content-Type: application/json

{
  "nome": "Pizza de Mussarela",
  "descricao": "Molho, mussarela e oregano",
  "valorCompra": 24.50,
  "valorVenda": 45.90,
  "quantidadeEstoque": 20,
  "codStatus": true
}

### Atualizar produto
PUT http://localhost:8080/api/v1/produtos/1
Content-Type: application/json

{
  "nome": "Pizza de Calabresa",
  "descricao": "Calabresa, cebola e mussarela",
  "valorCompra": 27.50,
  "valorVenda": 49.90,
  "quantidadeEstoque": 15,
  "codStatus": true
}

### Excluir produto
DELETE http://localhost:8080/api/v1/produtos/1

