spring.application.name=pizzarianeymar
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=pizzarianeymar;integratedSecurity=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
